/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import connection.Conexao;

/**
 *
 * @author 007
 */
public class SistemaUI extends javax.swing.JFrame {

    /**
     * Creates new form SistemaUI
     */
    public SistemaUI() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel_clientes = new javax.swing.JPanel();
        jPanel_clientes_dados = new javax.swing.JPanel();
        jLabel_cliente_modo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField_cliente_nome = new javax.swing.JTextField();
        jTextField_cliente_email = new javax.swing.JTextField();
        jTextField_cliente_telefone = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField_cliente_rua = new javax.swing.JTextField();
        jTextField_cliente_ruaNum = new javax.swing.JTextField();
        jTextField_cliente_cep = new javax.swing.JTextField();
        jTextField_cliente_cidade = new javax.swing.JTextField();
        jComboBox_cliente_estado = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jTextField_cliente_documento = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea_cliente_infos = new javax.swing.JTextArea();
        jButton_cliente_confirmar = new javax.swing.JButton();
        jButton_cliente_voltar = new javax.swing.JButton();
        jPanel_clientes_lista = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_clientes = new javax.swing.JTable();
        jButton_cliente_adicionar = new javax.swing.JButton();
        jButton_cliente_editar = new javax.swing.JButton();
        jButton_cliente_remover = new javax.swing.JButton();
        jButton_cliente_pesquisa = new javax.swing.JButton();
        jButton_cliente_limpar = new javax.swing.JButton();
        jTextField_Cliente_Pesquisa = new javax.swing.JTextField();
        jPanel_produtos = new javax.swing.JPanel();
        jPanel_produtos_dados = new javax.swing.JPanel();
        jLabel_produto_modo = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField_produto_nome = new javax.swing.JTextField();
        jTextField_produto_detalhes = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jRadioButton_alimenticio = new javax.swing.JRadioButton();
        jRadioButton_higiene = new javax.swing.JRadioButton();
        jRadioButton_limpeza = new javax.swing.JRadioButton();
        jRadioButton_outros = new javax.swing.JRadioButton();
        jLabel16 = new javax.swing.JLabel();
        jTextField_produto_valor = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextField_produto_quantidade = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jCheckBox_produto_fornecedor = new javax.swing.JCheckBox();
        jButton_produto_confirmar = new javax.swing.JButton();
        jButton_produto_voltar = new javax.swing.JButton();
        jPanel_produtos_lista = new javax.swing.JPanel();
        jTextField_produto_pesquisa = new javax.swing.JTextField();
        jButton_produto_pesquisar = new javax.swing.JButton();
        jButton_produto_limpar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable_produtos = new javax.swing.JTable();
        jButton_produto_adicionar = new javax.swing.JButton();
        jButton_produto_editar = new javax.swing.JButton();
        jButton_produto_remover = new javax.swing.JButton();
        jPanel_pedidos = new javax.swing.JPanel();
        jPanel_pedidos_lista = new javax.swing.JPanel();
        jTextField_pedido_pesquisa = new javax.swing.JTextField();
        jButton_pedido_pesquisar = new javax.swing.JButton();
        jButton_pedido_limpar = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable_pedidos = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable_itens = new javax.swing.JTable();
        jButton_pedido_carregar = new javax.swing.JButton();
        jButton_pedido_adicionar = new javax.swing.JButton();
        jButton_pedido_remover = new javax.swing.JButton();
        jPanel_pedidos_dados = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox_pedido_cliente = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        jComboBox_pedido_produto = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable_compra = new javax.swing.JTable();
        jLabel21 = new javax.swing.JLabel();
        jTextField_compra_quantidade = new javax.swing.JTextField();
        jButton_compra_quantidade = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel_compra_total = new javax.swing.JLabel();
        jButton_pedido_confirmar = new javax.swing.JButton();
        jButton_pedido_voltar = new javax.swing.JButton();
        jButton_compra_remover = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel_clientes.setLayout(new java.awt.CardLayout());

        jLabel_cliente_modo.setText("Novo Cliente");

        jLabel2.setText("Nome");

        jLabel3.setText("E-mail");

        jLabel4.setText("Telefone");

        jLabel5.setText("Endereço");

        jLabel6.setText("Rua");

        jLabel7.setText("Número");

        jLabel8.setText("CEP");

        jLabel9.setText("Cidade");

        jLabel10.setText("Estado");

        jComboBox_cliente_estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Acre", "Alagoas", "Amapá", "Amazonas", "Bahia", "Ceará", "Distrito Federal", "Espírito Santo", "Goiás", "Maranhão", "Mato Grosso", "Mato Grosso do Sul", "Minas Gerais", "Pará", "Paraíba", "Paraná", "Pernambuco", "Piauí", "Rio de Janeiro", "Rio Grande do Norte", "Rio Grande do Sul", "Rondônia", "Roraima", "Santa Catarina", "São Paulo", "Sergipe", "Tocantins" }));

        jLabel11.setText("Dcumento");

        jTextField_cliente_documento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_cliente_documentoActionPerformed(evt);
            }
        });

        jLabel12.setText("Informações Adicionais");

        jTextArea_cliente_infos.setColumns(20);
        jTextArea_cliente_infos.setRows(5);
        jScrollPane2.setViewportView(jTextArea_cliente_infos);

        jButton_cliente_confirmar.setText("Confirmar");

        jButton_cliente_voltar.setText("Voltar");
        jButton_cliente_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cliente_voltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_clientes_dadosLayout = new javax.swing.GroupLayout(jPanel_clientes_dados);
        jPanel_clientes_dados.setLayout(jPanel_clientes_dadosLayout);
        jPanel_clientes_dadosLayout.setHorizontalGroup(
            jPanel_clientes_dadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_clientes_dadosLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel_clientes_dadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_clientes_dadosLayout.createSequentialGroup()
                        .addGroup(jPanel_clientes_dadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel5)
                            .addComponent(jLabel_cliente_modo))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_clientes_dadosLayout.createSequentialGroup()
                        .addGroup(jPanel_clientes_dadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_clientes_dadosLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_clientes_dadosLayout.createSequentialGroup()
                                .addGroup(jPanel_clientes_dadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel_clientes_dadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_cliente_email)
                                    .addComponent(jTextField_cliente_nome)
                                    .addComponent(jTextField_cliente_telefone))))
                        .addGap(282, 282, 282))
                    .addGroup(jPanel_clientes_dadosLayout.createSequentialGroup()
                        .addGroup(jPanel_clientes_dadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField_cliente_documento, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel_clientes_dadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel_clientes_dadosLayout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextField_cliente_rua, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel_clientes_dadosLayout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextField_cliente_cidade, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_clientes_dadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_clientes_dadosLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBox_cliente_estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel_clientes_dadosLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_cliente_ruaNum, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_cliente_cep, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 68, Short.MAX_VALUE))))
                    .addGroup(jPanel_clientes_dadosLayout.createSequentialGroup()
                        .addGroup(jPanel_clientes_dadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_clientes_dadosLayout.createSequentialGroup()
                                .addComponent(jButton_cliente_confirmar)
                                .addGap(18, 18, 18)
                                .addComponent(jButton_cliente_voltar))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 711, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel_clientes_dadosLayout.setVerticalGroup(
            jPanel_clientes_dadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_clientes_dadosLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel_cliente_modo)
                .addGap(18, 18, 18)
                .addGroup(jPanel_clientes_dadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField_cliente_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_clientes_dadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField_cliente_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_clientes_dadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField_cliente_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(jLabel5)
                .addGap(26, 26, 26)
                .addGroup(jPanel_clientes_dadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jTextField_cliente_rua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_cliente_ruaNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_cliente_cep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel_clientes_dadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jTextField_cliente_cidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_cliente_estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_clientes_dadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextField_cliente_documento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_clientes_dadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_cliente_confirmar)
                    .addComponent(jButton_cliente_voltar))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jPanel_clientes.add(jPanel_clientes_dados, "card3");

        jTable_clientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Email", "Telefone", "CEP", "Rua", "Número", "Cidade", "Estado", "Documento", "Infos"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable_clientes);

        jButton_cliente_adicionar.setText("Adicionar");

        jButton_cliente_editar.setText("Editar");

        jButton_cliente_remover.setText("Remover");

        jButton_cliente_pesquisa.setText("Pesquisar");

        jButton_cliente_limpar.setText("Limpar");

        javax.swing.GroupLayout jPanel_clientes_listaLayout = new javax.swing.GroupLayout(jPanel_clientes_lista);
        jPanel_clientes_lista.setLayout(jPanel_clientes_listaLayout);
        jPanel_clientes_listaLayout.setHorizontalGroup(
            jPanel_clientes_listaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_clientes_listaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_clientes_listaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 793, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_clientes_listaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jTextField_Cliente_Pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_cliente_pesquisa)
                        .addGap(12, 12, 12)
                        .addComponent(jButton_cliente_limpar)
                        .addGap(237, 237, 237))
                    .addGroup(jPanel_clientes_listaLayout.createSequentialGroup()
                        .addComponent(jButton_cliente_adicionar)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_cliente_editar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_cliente_remover)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel_clientes_listaLayout.setVerticalGroup(
            jPanel_clientes_listaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_clientes_listaLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(jPanel_clientes_listaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_cliente_pesquisa)
                    .addComponent(jButton_cliente_limpar)
                    .addComponent(jTextField_Cliente_Pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addGroup(jPanel_clientes_listaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_cliente_adicionar)
                    .addComponent(jButton_cliente_editar)
                    .addComponent(jButton_cliente_remover))
                .addContainerGap(208, Short.MAX_VALUE))
        );

        jPanel_clientes.add(jPanel_clientes_lista, "card2");

        jTabbedPane1.addTab("Clientes", jPanel_clientes);

        jPanel_produtos.setLayout(new java.awt.CardLayout());

        jLabel_produto_modo.setText("Novo Produto");

        jLabel13.setText("Nome");

        jLabel14.setText("Detalhes");

        jLabel15.setText("Tipo");

        buttonGroup1.add(jRadioButton_alimenticio);
        jRadioButton_alimenticio.setText("Alimenticio");
        jRadioButton_alimenticio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_alimenticioActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton_higiene);
        jRadioButton_higiene.setText("Higiene");
        jRadioButton_higiene.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_higieneActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton_limpeza);
        jRadioButton_limpeza.setText("Limpeza");

        buttonGroup1.add(jRadioButton_outros);
        jRadioButton_outros.setSelected(true);
        jRadioButton_outros.setText("Outros");

        jLabel16.setText("Valor Unitário");

        jLabel17.setText("Quantidade");

        jTextField_produto_quantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_produto_quantidadeActionPerformed(evt);
            }
        });

        jLabel18.setText("Possui um fornecedor ativo:");

        jCheckBox_produto_fornecedor.setText("Sim");

        jButton_produto_confirmar.setText("Confirmar");

        jButton_produto_voltar.setText("Voltar");

        javax.swing.GroupLayout jPanel_produtos_dadosLayout = new javax.swing.GroupLayout(jPanel_produtos_dados);
        jPanel_produtos_dados.setLayout(jPanel_produtos_dadosLayout);
        jPanel_produtos_dadosLayout.setHorizontalGroup(
            jPanel_produtos_dadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_produtos_dadosLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel_produtos_dadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(jLabel_produto_modo)
                    .addGroup(jPanel_produtos_dadosLayout.createSequentialGroup()
                        .addGroup(jPanel_produtos_dadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13)
                            .addComponent(jLabel15))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_produtos_dadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_produtos_dadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextField_produto_nome)
                                .addComponent(jTextField_produto_detalhes, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE))
                            .addGroup(jPanel_produtos_dadosLayout.createSequentialGroup()
                                .addComponent(jRadioButton_alimenticio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton_higiene)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel_produtos_dadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel_produtos_dadosLayout.createSequentialGroup()
                                        .addComponent(jRadioButton_limpeza)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jRadioButton_outros))
                                    .addGroup(jPanel_produtos_dadosLayout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField_produto_quantidade))))))
                    .addGroup(jPanel_produtos_dadosLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_produto_valor, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_produtos_dadosLayout.createSequentialGroup()
                        .addGroup(jPanel_produtos_dadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton_produto_confirmar, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                            .addComponent(jCheckBox_produto_fornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(33, 33, 33)
                        .addComponent(jButton_produto_voltar)))
                .addContainerGap(411, Short.MAX_VALUE))
        );
        jPanel_produtos_dadosLayout.setVerticalGroup(
            jPanel_produtos_dadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_produtos_dadosLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel_produto_modo)
                .addGap(29, 29, 29)
                .addGroup(jPanel_produtos_dadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTextField_produto_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_produtos_dadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jTextField_produto_detalhes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel_produtos_dadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_produtos_dadosLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel15))
                    .addGroup(jPanel_produtos_dadosLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel_produtos_dadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton_alimenticio)
                            .addComponent(jRadioButton_higiene)
                            .addComponent(jRadioButton_limpeza)
                            .addComponent(jRadioButton_outros))))
                .addGap(33, 33, 33)
                .addGroup(jPanel_produtos_dadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jTextField_produto_valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(jTextField_produto_quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox_produto_fornecedor)
                .addGap(69, 69, 69)
                .addGroup(jPanel_produtos_dadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_produto_confirmar)
                    .addComponent(jButton_produto_voltar))
                .addContainerGap(136, Short.MAX_VALUE))
        );

        jPanel_produtos.add(jPanel_produtos_dados, "card3");

        jButton_produto_pesquisar.setText("Pesquisar");

        jButton_produto_limpar.setText("Limpar");

        jTable_produtos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Detalhes", "Tipo", "Valor Unitátiro", "Quantidade", "Fornecedor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable_produtos);

        jButton_produto_adicionar.setText("Adicionar");

        jButton_produto_editar.setText("Editar");

        jButton_produto_remover.setText("Remover");

        javax.swing.GroupLayout jPanel_produtos_listaLayout = new javax.swing.GroupLayout(jPanel_produtos_lista);
        jPanel_produtos_lista.setLayout(jPanel_produtos_listaLayout);
        jPanel_produtos_listaLayout.setHorizontalGroup(
            jPanel_produtos_listaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_produtos_listaLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel_produtos_listaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_produtos_listaLayout.createSequentialGroup()
                        .addComponent(jButton_produto_adicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_produto_editar)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_produto_remover))
                    .addGroup(jPanel_produtos_listaLayout.createSequentialGroup()
                        .addComponent(jTextField_produto_pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_produto_pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_produto_limpar))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 746, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel_produtos_listaLayout.setVerticalGroup(
            jPanel_produtos_listaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_produtos_listaLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel_produtos_listaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_produto_pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_produto_pesquisar)
                    .addComponent(jButton_produto_limpar))
                .addGap(37, 37, 37)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(jPanel_produtos_listaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_produto_adicionar)
                    .addComponent(jButton_produto_editar)
                    .addComponent(jButton_produto_remover))
                .addContainerGap(285, Short.MAX_VALUE))
        );

        jPanel_produtos.add(jPanel_produtos_lista, "card2");

        jTabbedPane1.addTab("Produtos", jPanel_produtos);

        jPanel_pedidos.setLayout(new java.awt.CardLayout());

        jTextField_pedido_pesquisa.setToolTipText("");

        jButton_pedido_pesquisar.setText("Pesquisar");

        jButton_pedido_limpar.setText("Limpar");

        jTable_pedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nota", "Cliente ID", "Valor Total", "Data"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Double.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTable_pedidos);

        jTable_itens.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nota", "Produto ID", "Quantidade", "Valor Unitário", "Valor Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(jTable_itens);

        jButton_pedido_carregar.setText("Carregar");

        jButton_pedido_adicionar.setText("Adicionar");

        jButton_pedido_remover.setText("Remover");

        javax.swing.GroupLayout jPanel_pedidos_listaLayout = new javax.swing.GroupLayout(jPanel_pedidos_lista);
        jPanel_pedidos_lista.setLayout(jPanel_pedidos_listaLayout);
        jPanel_pedidos_listaLayout.setHorizontalGroup(
            jPanel_pedidos_listaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_pedidos_listaLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel_pedidos_listaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_pedidos_listaLayout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 674, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(105, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_pedidos_listaLayout.createSequentialGroup()
                        .addComponent(jTextField_pedido_pesquisa)
                        .addGap(31, 31, 31)
                        .addComponent(jButton_pedido_pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_pedido_limpar)
                        .addGap(299, 299, 299))
                    .addGroup(jPanel_pedidos_listaLayout.createSequentialGroup()
                        .addGroup(jPanel_pedidos_listaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_pedido_carregar)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 674, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel_pedidos_listaLayout.createSequentialGroup()
                                .addComponent(jButton_pedido_adicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton_pedido_remover)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel_pedidos_listaLayout.setVerticalGroup(
            jPanel_pedidos_listaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_pedidos_listaLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel_pedidos_listaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_pedido_pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_pedido_pesquisar)
                    .addComponent(jButton_pedido_limpar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(jButton_pedido_carregar)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel_pedidos_listaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_pedido_adicionar)
                    .addComponent(jButton_pedido_remover))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        jPanel_pedidos.add(jPanel_pedidos_lista, "card2");

        jLabel1.setText("Cliente");

        jLabel19.setText("Produto");

        jLabel20.setText("Lista de Produtos do Pedido:");

        jTable_compra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Produto ID", "Produto Nome", "Quantidade", "Valor Unitário", "Valor Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(jTable_compra);

        jLabel21.setText("Quantidade do Produto Selecionado:");

        jButton_compra_quantidade.setText("Alterar");

        jLabel22.setText("Valor Total: R$");

        jLabel_compra_total.setText("0,00");

        jButton_pedido_confirmar.setText("Confirmar");
        jButton_pedido_confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_pedido_confirmarActionPerformed(evt);
            }
        });

        jButton_pedido_voltar.setText("Voltar");

        jButton_compra_remover.setText("Remover");

        javax.swing.GroupLayout jPanel_pedidos_dadosLayout = new javax.swing.GroupLayout(jPanel_pedidos_dados);
        jPanel_pedidos_dados.setLayout(jPanel_pedidos_dadosLayout);
        jPanel_pedidos_dadosLayout.setHorizontalGroup(
            jPanel_pedidos_dadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_pedidos_dadosLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel_pedidos_dadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_pedidos_dadosLayout.createSequentialGroup()
                        .addComponent(jButton_pedido_confirmar)
                        .addGap(46, 46, 46)
                        .addComponent(jButton_pedido_voltar))
                    .addGroup(jPanel_pedidos_dadosLayout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_compra_total))
                    .addGroup(jPanel_pedidos_dadosLayout.createSequentialGroup()
                        .addGroup(jPanel_pedidos_dadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_pedidos_dadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox_pedido_produto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox_pedido_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel20)
                    .addGroup(jPanel_pedidos_dadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel_pedidos_dadosLayout.createSequentialGroup()
                            .addComponent(jLabel21)
                            .addGap(18, 18, 18)
                            .addComponent(jTextField_compra_quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jButton_compra_quantidade)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_compra_remover))
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 712, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel_pedidos_dadosLayout.setVerticalGroup(
            jPanel_pedidos_dadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_pedidos_dadosLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel_pedidos_dadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox_pedido_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel_pedidos_dadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jComboBox_pedido_produto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jLabel20)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(jPanel_pedidos_dadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jTextField_compra_quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_compra_quantidade)
                    .addComponent(jButton_compra_remover))
                .addGap(33, 33, 33)
                .addGroup(jPanel_pedidos_dadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel_compra_total))
                .addGap(48, 48, 48)
                .addGroup(jPanel_pedidos_dadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_pedido_confirmar)
                    .addComponent(jButton_pedido_voltar))
                .addContainerGap(79, Short.MAX_VALUE))
        );

        jPanel_pedidos.add(jPanel_pedidos_dados, "card3");

        jTabbedPane1.addTab("Pedidos", jPanel_pedidos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_cliente_documentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_cliente_documentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_cliente_documentoActionPerformed

    private void jButton_cliente_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cliente_voltarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_cliente_voltarActionPerformed

    private void jRadioButton_alimenticioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_alimenticioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton_alimenticioActionPerformed

    private void jRadioButton_higieneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_higieneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton_higieneActionPerformed

    private void jTextField_produto_quantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_produto_quantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_produto_quantidadeActionPerformed

    private void jButton_pedido_confirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_pedido_confirmarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_pedido_confirmarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SistemaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SistemaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SistemaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SistemaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SistemaUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton_cliente_adicionar;
    private javax.swing.JButton jButton_cliente_confirmar;
    private javax.swing.JButton jButton_cliente_editar;
    private javax.swing.JButton jButton_cliente_limpar;
    private javax.swing.JButton jButton_cliente_pesquisa;
    private javax.swing.JButton jButton_cliente_remover;
    private javax.swing.JButton jButton_cliente_voltar;
    private javax.swing.JButton jButton_compra_quantidade;
    private javax.swing.JButton jButton_compra_remover;
    private javax.swing.JButton jButton_pedido_adicionar;
    private javax.swing.JButton jButton_pedido_carregar;
    private javax.swing.JButton jButton_pedido_confirmar;
    private javax.swing.JButton jButton_pedido_limpar;
    private javax.swing.JButton jButton_pedido_pesquisar;
    private javax.swing.JButton jButton_pedido_remover;
    private javax.swing.JButton jButton_pedido_voltar;
    private javax.swing.JButton jButton_produto_adicionar;
    private javax.swing.JButton jButton_produto_confirmar;
    private javax.swing.JButton jButton_produto_editar;
    private javax.swing.JButton jButton_produto_limpar;
    private javax.swing.JButton jButton_produto_pesquisar;
    private javax.swing.JButton jButton_produto_remover;
    private javax.swing.JButton jButton_produto_voltar;
    private javax.swing.JCheckBox jCheckBox_produto_fornecedor;
    private javax.swing.JComboBox<String> jComboBox_cliente_estado;
    private javax.swing.JComboBox<Object> jComboBox_pedido_cliente;
    private javax.swing.JComboBox<Object> jComboBox_pedido_produto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_cliente_modo;
    private javax.swing.JLabel jLabel_compra_total;
    private javax.swing.JLabel jLabel_produto_modo;
    private javax.swing.JPanel jPanel_clientes;
    private javax.swing.JPanel jPanel_clientes_dados;
    private javax.swing.JPanel jPanel_clientes_lista;
    private javax.swing.JPanel jPanel_pedidos;
    private javax.swing.JPanel jPanel_pedidos_dados;
    private javax.swing.JPanel jPanel_pedidos_lista;
    private javax.swing.JPanel jPanel_produtos;
    private javax.swing.JPanel jPanel_produtos_dados;
    private javax.swing.JPanel jPanel_produtos_lista;
    private javax.swing.JRadioButton jRadioButton_alimenticio;
    private javax.swing.JRadioButton jRadioButton_higiene;
    private javax.swing.JRadioButton jRadioButton_limpeza;
    private javax.swing.JRadioButton jRadioButton_outros;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable_clientes;
    private javax.swing.JTable jTable_compra;
    private javax.swing.JTable jTable_itens;
    private javax.swing.JTable jTable_pedidos;
    private javax.swing.JTable jTable_produtos;
    private javax.swing.JTextArea jTextArea_cliente_infos;
    private javax.swing.JTextField jTextField_Cliente_Pesquisa;
    private javax.swing.JTextField jTextField_cliente_cep;
    private javax.swing.JTextField jTextField_cliente_cidade;
    private javax.swing.JTextField jTextField_cliente_documento;
    private javax.swing.JTextField jTextField_cliente_email;
    private javax.swing.JTextField jTextField_cliente_nome;
    private javax.swing.JTextField jTextField_cliente_rua;
    private javax.swing.JTextField jTextField_cliente_ruaNum;
    private javax.swing.JTextField jTextField_cliente_telefone;
    private javax.swing.JTextField jTextField_compra_quantidade;
    private javax.swing.JTextField jTextField_pedido_pesquisa;
    private javax.swing.JTextField jTextField_produto_detalhes;
    private javax.swing.JTextField jTextField_produto_nome;
    private javax.swing.JTextField jTextField_produto_pesquisa;
    private javax.swing.JTextField jTextField_produto_quantidade;
    private javax.swing.JTextField jTextField_produto_valor;
    // End of variables declaration//GEN-END:variables
}
